worker_processes 1; # Определяет количество рабочих процессов

events {
    worker_connections 1024; # максимальное кол-во подключений
}


http {
    include mime.types;
    default_type application/octet-stream;
    sendfile on;
    keepalive_timeout 65;

    server {
        listen 80;
        server_name _;

        location / {
            root /var/www/html;
            index index.html;
            try_files $uri $uri.html $uri/ =404;
        }
        # error_page 500 502 503 504 /50x.html;
        # location = /50x.html {
        #     root html;
        # }
    }
}