worker_processes 1; # Определяет количество рабочих процессов

events {
    worker_connections 1024; # максимальное кол-во подключений
}


http {
    include mime.types;
    default_type application/octet-stream;
    sendfile on;
    keepalive_timeout 65;

    server {
        listen 80;
        server_name _;

        location / {
            root /var/www/html;
            index index.html;
            try_files $uri $uri.html $uri/ =404;
        }
        
        location /swagger/ {
            proxy_pass http://backend:8080/swagger/;
            proxy_http_version 1.1;
            proxy_set_header Host $host;
        }
            
        location /api/ {
            proxy_pass http://backend:8080/api/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
        # error_page 500 502 503 504 /50x.html;
        # location = /50x.html {
        #     root html;
        # }
    }
}