// <auto-generated />
using System;
using Infrastructure.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations.Metrics
{
    [DbContext(typeof(MetricsContext))]
    partial class MetricsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Infrastructure.Entities.FilteredProjectView", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("FilterSessionId")
                        .HasColumnType("uuid");

                    b.Property<bool>("HasFilter")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("OpenedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FilterSessionId");

                    b.ToTable("FilteredProjectViews");
                });

            modelBuilder.Entity("Infrastructure.Entities.FilteredView", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Filter")
                        .HasColumnType("jsonb");

                    b.Property<Guid>("FilterSessionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("OpenedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Page")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FilterSessionId");

                    b.ToTable("FilteredViews");
                });

            modelBuilder.Entity("Infrastructure.Entities.RetentionByCohort", b =>
                {
                    b.Property<DateOnly>("CohortDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("CohortWeek")
                        .HasColumnType("date");

                    b.Property<int>("Users")
                        .HasColumnType("integer");

                    b.Property<int>("r14D")
                        .HasColumnType("integer");

                    b.Property<int>("r30D")
                        .HasColumnType("integer");

                    b.Property<int>("r7D")
                        .HasColumnType("integer");

                    b.HasKey("CohortDate");

                    b.ToTable("RetentionByCohorts");
                });

            modelBuilder.Entity("Infrastructure.Entities.UserRetentionState", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("FirstOpen")
                        .HasColumnType("date");

                    b.Property<DateOnly>("SecondOpen")
                        .HasColumnType("date");

                    b.Property<bool>("r14D")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("r30D")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("r7D")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.HasKey("UserId");

                    b.ToTable("UserRetentionStates");
                });
#pragma warning restore 612, 618
        }
    }
}
