apiVersion: 1

datasources:
  - name: Banana Prometheus
    uid: banana-prometheus
    type: prometheus
    access: proxy
    url: prometheus:9090
    isDefault: false
    jsonData:
      httpMethod: POST
      manageAlerts: false
