name: Deploy to Server

on:
  workflow_run:
    workflows: [".NET Tests"]
    types: 
      - completed

#штука чтобы одновременно мог выполняться только один деплой:
concurrency:
  group: deploy-${{ github.event.workflow_run.head_branch }}
  cancel-in-progress: true

jobs:
  deploy:
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      (github.event.workflow_run.head_branch == 'main' || github.event.workflow_run.head_branch == 'dev')
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1 #выполняем команды на actione
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            set -e 
            
            if [ ! -d ~/app ]; then
              mkdir -p ~/app
            fi
            
            cd ~/app
            
            if [ ! -d .git ]; then
              git clone https://github.com/Jlychee/Blueprint.git .
            fi
            
            git fetch origin
            
            if [ "${{ github.event.workflow_run.head_branch }}" = "main" ]; then
              git reset --hard origin/main
            else
              git reset --hard origin/dev
            fi
            
            docker compose up -d --build
            docker compose ps